config/routes.rb
Rails.application.routes.draw do
    get 'index' => 'pages#index'
    get 'about' => 'pages#about'
    get 'contact' => 'pages#contact'
    get 'images' => 'pages#images'
    get 'videos' => 'pages#videos'
    get 'games' => 'pages#games'
    
    root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
    end
    
    def about
    end
    
    def images
    end
    
    def videos
    end
    
    def games
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def header_centering style=''
   end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  
  <head>
    <title>Infinity Gaming | Main page</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  
</html>

app/views/pages/about.html.erb
<%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'shared/application_nav_second' %>
<%= render 'shared/about_content' %>

app/views/pages/contact.html.erb
<%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'shared/application_nav_second' %>
<div class="pages-content">
   <h1>Contact information</h1>
</div>

app/views/pages/games.html.erb
<%= stylesheet_link_tag'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'shared/application_nav_second' %>
<div class="pages-content">
  <div class="header-con">
    <div class="header-text-con" id="f">
      <h1>
        <span class="overlay">Games</span>
        <script>
        var windw = this;
        $.fn.followTo = function ( pos ) {
            var $this = this,
                $window = $(windw);

            $window.scroll(function(e){
                if ($window.scrollTop() > pos) {
                    $this.css({
                        position: 'absolute',
                        top: pos
                    });
                } else {
                    $this.css({
                        position: 'fixed',
                        top: 0
                    });
                }
            });
        };
        $('#f').followTo(900);
        </script>
      </h1>
    </div>
  </div>
  <div class="games-con">
    <% 8.times do %>
      <%= render 'shared/game' %>
    <% end %>
  </div>
</div>

app/views/pages/images.html.erb
<%= stylesheet_link_tag    'pages', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= render 'shared/application_nav_second' %>
<%= image_tag("luncheon.jpg", :alt => "The luncheon", width: '60%', height: '50%', class: 'header-centering') %>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en-us">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => "reload" %>
  <body>
    
    <!-- Application navigation partial located in shared/_application_nav.html.erb file -->
    
    <%= render 'shared/application_nav' %>
    
    <!-- Application content partial located in shared/_application_content.html.erb file -->
    
    <%= render 'shared/application_content' %>
    
  </body>
  
</html>

app/views/pages/videos.html.erb
<%= render 'shared/application_nav_second' %>

app/views/shared/_about_content.html.erb
<div class="about-header-div">
   <h1 class="about-header"> Our team of developers </h1>
</div>


<div class="developers">
   <div class="row">
     <div class="col-xs-6 col-md-3 first-image">
         <img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzEwMCV4MTgwCkNyZWF0ZWQgd2l0aCBIb2xkZXIuanMgMi42LjAuCkxlYXJuIG1vcmUgYXQgaHR0cDovL2hvbGRlcmpzLmNvbQooYykgMjAxMi0yMDE1IEl2YW4gTWFsb3BpbnNreSAtIGh0dHA6Ly9pbXNreS5jbwotLT48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPjwhW0NEQVRBWyNob2xkZXJfMTVkYjA0YzBkMzcgdGV4dCB7IGZpbGw6I0FBQUFBQTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0IH0gXV0+PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImhvbGRlcl8xNWRiMDRjMGQzNyI+PHJlY3Qgd2lkdGg9IjE3MSIgaGVpZ2h0PSIxODAiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSI2MC41IiB5PSI5NC44Ij4xNzF4MTgwPC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="...">
         <p> Emil Seyidov</p>
     </div>
   </div>
   
   <div class="row">
     <div class="col-xs-6 col-md-3 second-image">
         <img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzEwMCV4MTgwCkNyZWF0ZWQgd2l0aCBIb2xkZXIuanMgMi42LjAuCkxlYXJuIG1vcmUgYXQgaHR0cDovL2hvbGRlcmpzLmNvbQooYykgMjAxMi0yMDE1IEl2YW4gTWFsb3BpbnNreSAtIGh0dHA6Ly9pbXNreS5jbwotLT48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPjwhW0NEQVRBWyNob2xkZXJfMTVkYjA0YzBkMzcgdGV4dCB7IGZpbGw6I0FBQUFBQTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0IH0gXV0+PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImhvbGRlcl8xNWRiMDRjMGQzNyI+PHJlY3Qgd2lkdGg9IjE3MSIgaGVpZ2h0PSIxODAiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSI2MC41IiB5PSI5NC44Ij4xNzF4MTgwPC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="...">
         <p>Carter Wilde</p>
     </div>
     
   </div>
   
   <div class="row">
     <div class="col-xs-6 col-md-3 third-image">
        <img src="data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiIHN0YW5kYWxvbmU9InllcyI/PjxzdmcgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB3aWR0aD0iMTcxIiBoZWlnaHQ9IjE4MCIgdmlld0JveD0iMCAwIDE3MSAxODAiIHByZXNlcnZlQXNwZWN0UmF0aW89Im5vbmUiPjwhLS0KU291cmNlIFVSTDogaG9sZGVyLmpzLzEwMCV4MTgwCkNyZWF0ZWQgd2l0aCBIb2xkZXIuanMgMi42LjAuCkxlYXJuIG1vcmUgYXQgaHR0cDovL2hvbGRlcmpzLmNvbQooYykgMjAxMi0yMDE1IEl2YW4gTWFsb3BpbnNreSAtIGh0dHA6Ly9pbXNreS5jbwotLT48ZGVmcz48c3R5bGUgdHlwZT0idGV4dC9jc3MiPjwhW0NEQVRBWyNob2xkZXJfMTVkYjA0YzBkMzcgdGV4dCB7IGZpbGw6I0FBQUFBQTtmb250LXdlaWdodDpib2xkO2ZvbnQtZmFtaWx5OkFyaWFsLCBIZWx2ZXRpY2EsIE9wZW4gU2Fucywgc2Fucy1zZXJpZiwgbW9ub3NwYWNlO2ZvbnQtc2l6ZToxMHB0IH0gXV0+PC9zdHlsZT48L2RlZnM+PGcgaWQ9ImhvbGRlcl8xNWRiMDRjMGQzNyI+PHJlY3Qgd2lkdGg9IjE3MSIgaGVpZ2h0PSIxODAiIGZpbGw9IiNFRUVFRUUiLz48Zz48dGV4dCB4PSI2MC41IiB5PSI5NC44Ij4xNzF4MTgwPC90ZXh0PjwvZz48L2c+PC9zdmc+" alt="...">
        <p>Porter</p>
     </div>
     
   </div>
</div>

app/views/shared/_about_nav.html.erb
<div class="nav-bar-con" data-toggle="open" style="z-index:5000" id="navbarCollapse">
  <div class="nav-bar-content" data-toggle="open" id="navbarCollapse">
    <div class="nav-bar-header">
      <form class="nav-bar-header-con">
        <button class="search-button" type="submit">SEARCH</button>
        <input class="search-box" type="text" placeholder="SEARCH">
      </form>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= root_path %>"><p>HOME</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= about_path %>"><p>ABOUT</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= contact_path %>"><p>CONTACT</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= images_path %>"><p>IMAGES</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= videos_path %>"><p>VIDEOS</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= games_path %>"><p>GAMES</p></a>
    </div>
  </div>
  <div class="nav-bar-ham">
    <button class="hamburger hamburger--spin no-outline" type="button" data-toggle="is-active" data-target="#navbarCollapse">
      <a data-toggle="open" data-target="#navbarCollapse">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </a>
    </button>
    <script>
      var $hamburger = $(".hamburger");
      var $nav = $(".nav-bar-con");
      var $navCon = $(".nav-bar-content");
      $hamburger.on("click", function(e) {
        $hamburger.toggleClass("is-active");
        $nav.toggleClass("open");
        $navCon.toggleClass("open");
          // Do something else, like open/close menu
      });
    </script>
  </div>
</div>

app/views/shared/_application_content.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <img class="first-slide" src="#" alt="First slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-left">
          <h1>Example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="second-slide" src="#" alt="Second slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block">
          <h1>Another example headline.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="third-slide" src="#" alt="Third slide">
      <div class="container">
        <div class="carousel-caption d-none d-md-block text-right">
          <h1>One more for good measure.</h1>
          <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container marketing">

      <!-- Three columns of text below the carousel -->
      <div class="row">
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="rounded-circle" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-secondary" href="#" role="button">View details &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->


      <!-- START THE FEATURETTES -->

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 push-md-5">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5 pull-md-7">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

     <!-- Application footer partial located at shared/application_footer.html.erb file-->
     
     <%= render 'shared/application_footer' %>

</div><!-- /.container -->

app/views/shared/_application_footer.html.erb
<footer>        
  <p class="float-right"><a href="#">Back to top</a></p>
  <p>&copy; 2017 <span class="bold-footer"> Infinity Gaming</span>, Inc. </p>
</footer>

app/views/shared/_application_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">

    
        
    <a class="navbar-brand" href="#">Infinity Gaming</a>
        
    <div class="collapse navbar-collapse" id="navbarCollapse">
            <span class="nav-item active">
                <a class="nav-link" href="#">Home </a>
            </span>
            
            <span class="nav-item">
                <a class="nav-link" href="<%= about_path %>">About Us </a>
                <%#= link_to 'About Us', url: "#", class: 'nav-link' %>      
            </span>
            
            <span class="nav-item">
                <a class="nav-link" href="<%= contact_path %>">Contact </a>
                <%#= link_to 'About Us', url: "#", class: 'nav-link' %>      
            </span>
            
            <span class="nav-item">
                <a class="nav-link" href="<%= images_path %>">Images </a>
                <%#= link_to 'About Us', url: "#", class: 'nav-link' %>      
            </span>
            
            <span class="nav-item">
                <a class="nav-link" href="<%= videos_path %>">Videos </a>
                <%#= link_to 'About Us', url: "#", class: 'nav-link' %>      
            </span>
    </div>
    
    <div class="search-con">
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
      <button class="hamburger hamburger--spin hamburger-button" type="button" data-toggle="is-active" data-target="#navbarCollapse">
          <a data-toggle="collapse" data-target="#navbarCollapse">
            <span class="hamburger-box">
              <span class="hamburger-inner"></span>
            </span>
          </a>
        </button>
        <script>
          var $hamburger = $(".hamburger");
          $hamburger.on("click", function(e) {
            $hamburger.toggleClass("is-active");
              // Do something else, like open/close menu
          });
        </script>
      </button>
    </div>

</nav>

app/views/shared/_application_nav_second.html.erb
<div class="nav-bar-con" data-toggle="open" style="z-index:5000" id="navbarCollapse">
  <div class="nav-bar-content" data-toggle="open" id="navbarCollapse">
    <div class="nav-bar-header">
      <form class="nav-bar-header-con">
        <button class="search-button" type="submit">SEARCH</button>
        <input class="search-box" type="text" placeholder="SEARCH">
      </form>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= root_path %>"><p>HOME</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= about_path %>"><p>ABOUT</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= contact_path %>"><p>CONTACT</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= images_path %>"><p>IMAGES</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= videos_path %>"><p>VIDEOS</p></a>
    </div>
    <div class="nav-bar-links-con">
      <a class="nav-bar-links" href="<%= games_path %>"><p>GAMES</p></a>
    </div>
  </div>
  <div class="nav-bar-ham">
    <button class="hamburger hamburger--spin no-outline" type="button" data-toggle="is-active" data-target="#navbarCollapse">
      <a data-toggle="open" data-target="#navbarCollapse">
        <span class="hamburger-box">
          <span class="hamburger-inner"></span>
        </span>
      </a>
    </button>
    <script>
      var $hamburger = $(".hamburger");
      var $nav = $(".nav-bar-con");
      var $navCon = $(".nav-bar-content");
      $hamburger.on("click", function(e) {
        $hamburger.toggleClass("is-active");
        $nav.toggleClass("open");
        $navCon.toggleClass("open");
          // Do something else, like open/close menu
      });
    </script>
  </div>
</div>

app/views/shared/_game.html.erb
<div class="game-con">
  <h1>Title</h1>
  <div class="game-info-con">
    <div class="game-image-con">
      <img src="http://via.placeholder.com/800x500"/>
    </div>
    <div class="game-text-con">
      <h1>INFO</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    </div>
  </div>
</div>